properties([
  [$class: 'ParametersDefinitionProperty', parameterDefinitions: [
    [$class: 'StringParameterDefinition',
      name: 'param1',
      defaultValue: '',
      description: 'Greeting message'],
    [$class: 'StringParameterDefinition',
      name: 'param2',
      defaultValue: '',
      description: '2nd paramete']
  ]]
])

node {
    echo 'Hello world!'
    echo "Value for param1: ${params.param1}"
    echo "Value for param2: ${params.param2}"
}
