# Build the docker image using the local build in developer box
# To avoid downloading everything from the internet and using developer's cache

FROM openjdk:8-jdk

ARG JENKINS_REF=/usr/share/jenkins/ref
ARG JENKINS_HOME=/app/jenkins

ENV JENKINS_REF ${JENKINS_REF}
ENV JENKINS_HOME ${JENKINS_HOME}

USER root
RUN mkdir -p /app ${JENKINS_REF}/plugins ${JENKINS_REF}/casc

COPY app/target/appassembler /app
COPY vanilla-package/target/war/jenkins.war /usr/share/jenkins/jenkins.war
RUN unzip /usr/share/jenkins/jenkins.war -d ${JENKINS_HOME} && \
  rm -rf ${JENKINS_HOME}/scripts ${JENKINS_HOME}/jsbundles ${JENKINS_HOME}/css ${JENKINS_HOME}/images ${JENKINS_HOME}/help ${JENKINS_HOME}/WEB-INF/detached-plugins ${JENKINS_HOME}/winstone.jar ${JENKINS_HOME}/WEB-INF/jenkins-cli.jar ${JENKINS_HOME}/WEB-INF/lib/jna-4.5.2.jar
COPY vanilla-package/target/plugins ${JENKINS_REF}/plugins
COPY jenkinsfile-runner-launcher /app/bin

VOLUME ${JENKINS_REF}/casc

ENTRYPOINT ["/app/bin/jenkinsfile-runner-launcher"]

CMD ["run"]
