pipeline {
    agent any
    parameters {
        string(name: 'param1', defaultValue: '', description: 'Greeting message')
        string(name: 'param2', defaultValue: '', description: '2nd parameter')
    }
    stages {
        stage('Build') {
            echo 'Hello world!'
            echo "Value for param1: ${params.param1}"
            echo "Value for param2: ${params.param2}"
        }
    }
}
